name = "glimr"
version = "0.2.0"

description = "The Glimr Framework"
licences = ["MIT"]
repository = { type = "github", user = "glimr-org", repo = "framework" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 2.1.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
lustre = ">= 5.4.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
