name = "glimr"
version = "0.5.0"

description = "A batteries-included web framework for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "glimr-org", repo = "framework" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 2.1.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
pog = ">= 4.0.0 and < 5.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
